# Generated by Django 6.0.6 on 2026-06-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='original/')),
                ('edited_image', models.ImageField(blank=True, upload_to='edited/')),
                ('tags', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('nature', 'Nature'), ('travel', 'Travel'), ('people', 'People'), ('city', 'City'), ('other', 'Other')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
