# Generated by Django 6.0.6 on 2026-06-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='filter',
            field=models.CharField(default='vintage', max_length=20),
        ),
    ]
