# Generated by Django 6.0.6 on 2026-07-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='edited_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.TextField(),
        ),
    ]
